import { Pokemon } from "./pokemon";

export const POKEMON: Array<Pokemon> = [
  {
    id: 1,
    name: "Bulbasaur",
    firstType: "Grass",
    secondType: "Poison",
    total: 318,
    hp: 45,
    attack: 49,
    defense: 49,
    specialAttack: 65,
    specialDefense: 65,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 2,
    name: "Ivysaur",
    firstType: "Grass",
    secondType: "Poison",
    total: 405,
    hp: 60,
    attack: 62,
    defense: 63,
    specialAttack: 80,
    specialDefense: 80,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 3,
    name: "Venusaur",
    firstType: "Grass",
    secondType: "Poison",
    total: 525,
    hp: 80,
    attack: 82,
    defense: 83,
    specialAttack: 100,
    specialDefense: 100,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 3,
    name: "VenusaurMega Venusaur",
    firstType: "Grass",
    secondType: "Poison",
    total: 625,
    hp: 80,
    attack: 100,
    defense: 123,
    specialAttack: 122,
    specialDefense: 120,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 4,
    name: "Charmander",
    firstType: "Fire",
    secondType: "",
    total: 309,
    hp: 39,
    attack: 52,
    defense: 43,
    specialAttack: 60,
    specialDefense: 50,
    speed: 65,
    generation: 1,
    legendary: false
  },
  {
    id: 5,
    name: "Charmeleon",
    firstType: "Fire",
    secondType: "",
    total: 405,
    hp: 58,
    attack: 64,
    defense: 58,
    specialAttack: 80,
    specialDefense: 65,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 6,
    name: "Charizard",
    firstType: "Fire",
    secondType: "Flying",
    total: 534,
    hp: 78,
    attack: 84,
    defense: 78,
    specialAttack: 109,
    specialDefense: 85,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 6,
    name: "CharizardMega Charizard X",
    firstType: "Fire",
    secondType: "Dragon",
    total: 634,
    hp: 78,
    attack: 130,
    defense: 111,
    specialAttack: 130,
    specialDefense: 85,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 6,
    name: "CharizardMega Charizard Y",
    firstType: "Fire",
    secondType: "Flying",
    total: 634,
    hp: 78,
    attack: 104,
    defense: 78,
    specialAttack: 159,
    specialDefense: 115,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 7,
    name: "Squirtle",
    firstType: "Water",
    secondType: "",
    total: 314,
    hp: 44,
    attack: 48,
    defense: 65,
    specialAttack: 50,
    specialDefense: 64,
    speed: 43,
    generation: 1,
    legendary: false
  },
  {
    id: 8,
    name: "Wartortle",
    firstType: "Water",
    secondType: "",
    total: 405,
    hp: 59,
    attack: 63,
    defense: 80,
    specialAttack: 65,
    specialDefense: 80,
    speed: 58,
    generation: 1,
    legendary: false
  },
  {
    id: 9,
    name: "Blastoise",
    firstType: "Water",
    secondType: "",
    total: 530,
    hp: 79,
    attack: 83,
    defense: 100,
    specialAttack: 85,
    specialDefense: 105,
    speed: 78,
    generation: 1,
    legendary: false
  },
  {
    id: 9,
    name: "BlastoiseMega Blastoise",
    firstType: "Water",
    secondType: "",
    total: 630,
    hp: 79,
    attack: 103,
    defense: 120,
    specialAttack: 135,
    specialDefense: 115,
    speed: 78,
    generation: 1,
    legendary: false
  },
  {
    id: 10,
    name: "Caterpie",
    firstType: "Bug",
    secondType: "",
    total: 195,
    hp: 45,
    attack: 30,
    defense: 35,
    specialAttack: 20,
    specialDefense: 20,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 11,
    name: "Metapod",
    firstType: "Bug",
    secondType: "",
    total: 205,
    hp: 50,
    attack: 20,
    defense: 55,
    specialAttack: 25,
    specialDefense: 25,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 12,
    name: "Butterfree",
    firstType: "Bug",
    secondType: "Flying",
    total: 395,
    hp: 60,
    attack: 45,
    defense: 50,
    specialAttack: 90,
    specialDefense: 80,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 13,
    name: "Weedle",
    firstType: "Bug",
    secondType: "Poison",
    total: 195,
    hp: 40,
    attack: 35,
    defense: 30,
    specialAttack: 20,
    specialDefense: 20,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 14,
    name: "Kakuna",
    firstType: "Bug",
    secondType: "Poison",
    total: 205,
    hp: 45,
    attack: 25,
    defense: 50,
    specialAttack: 25,
    specialDefense: 25,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 15,
    name: "Beedrill",
    firstType: "Bug",
    secondType: "Poison",
    total: 395,
    hp: 65,
    attack: 90,
    defense: 40,
    specialAttack: 45,
    specialDefense: 80,
    speed: 75,
    generation: 1,
    legendary: false
  },
  {
    id: 15,
    name: "BeedrillMega Beedrill",
    firstType: "Bug",
    secondType: "Poison",
    total: 495,
    hp: 65,
    attack: 150,
    defense: 40,
    specialAttack: 15,
    specialDefense: 80,
    speed: 145,
    generation: 1,
    legendary: false
  },
  {
    id: 16,
    name: "Pidgey",
    firstType: "Normal",
    secondType: "Flying",
    total: 251,
    hp: 40,
    attack: 45,
    defense: 40,
    specialAttack: 35,
    specialDefense: 35,
    speed: 56,
    generation: 1,
    legendary: false
  },
  {
    id: 17,
    name: "Pidgeotto",
    firstType: "Normal",
    secondType: "Flying",
    total: 349,
    hp: 63,
    attack: 60,
    defense: 55,
    specialAttack: 50,
    specialDefense: 50,
    speed: 71,
    generation: 1,
    legendary: false
  },
  {
    id: 18,
    name: "Pidgeot",
    firstType: "Normal",
    secondType: "Flying",
    total: 479,
    hp: 83,
    attack: 80,
    defense: 75,
    specialAttack: 70,
    specialDefense: 70,
    speed: 101,
    generation: 1,
    legendary: false
  },
  {
    id: 18,
    name: "PidgeotMega Pidgeot",
    firstType: "Normal",
    secondType: "Flying",
    total: 579,
    hp: 83,
    attack: 80,
    defense: 80,
    specialAttack: 135,
    specialDefense: 80,
    speed: 121,
    generation: 1,
    legendary: false
  },
  {
    id: 19,
    name: "Rattata",
    firstType: "Normal",
    secondType: "",
    total: 253,
    hp: 30,
    attack: 56,
    defense: 35,
    specialAttack: 25,
    specialDefense: 35,
    speed: 72,
    generation: 1,
    legendary: false
  },
  {
    id: 20,
    name: "Raticate",
    firstType: "Normal",
    secondType: "",
    total: 413,
    hp: 55,
    attack: 81,
    defense: 60,
    specialAttack: 50,
    specialDefense: 70,
    speed: 97,
    generation: 1,
    legendary: false
  },
  {
    id: 21,
    name: "Spearow",
    firstType: "Normal",
    secondType: "Flying",
    total: 262,
    hp: 40,
    attack: 60,
    defense: 30,
    specialAttack: 31,
    specialDefense: 31,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 22,
    name: "Fearow",
    firstType: "Normal",
    secondType: "Flying",
    total: 442,
    hp: 65,
    attack: 90,
    defense: 65,
    specialAttack: 61,
    specialDefense: 61,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 23,
    name: "Ekans",
    firstType: "Poison",
    secondType: "",
    total: 288,
    hp: 35,
    attack: 60,
    defense: 44,
    specialAttack: 40,
    specialDefense: 54,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 24,
    name: "Arbok",
    firstType: "Poison",
    secondType: "",
    total: 438,
    hp: 60,
    attack: 85,
    defense: 69,
    specialAttack: 65,
    specialDefense: 79,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 25,
    name: "Pikachu",
    firstType: "Electric",
    secondType: "",
    total: 320,
    hp: 35,
    attack: 55,
    defense: 40,
    specialAttack: 50,
    specialDefense: 50,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 26,
    name: "Raichu",
    firstType: "Electric",
    secondType: "",
    total: 485,
    hp: 60,
    attack: 90,
    defense: 55,
    specialAttack: 90,
    specialDefense: 80,
    speed: 110,
    generation: 1,
    legendary: false
  },
  {
    id: 27,
    name: "Sandshrew",
    firstType: "Ground",
    secondType: "",
    total: 300,
    hp: 50,
    attack: 75,
    defense: 85,
    specialAttack: 20,
    specialDefense: 30,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 28,
    name: "Sandslash",
    firstType: "Ground",
    secondType: "",
    total: 450,
    hp: 75,
    attack: 100,
    defense: 110,
    specialAttack: 45,
    specialDefense: 55,
    speed: 65,
    generation: 1,
    legendary: false
  },
  {
    id: 29,
    name: "Nidoran♀",
    firstType: "Poison",
    secondType: "",
    total: 275,
    hp: 55,
    attack: 47,
    defense: 52,
    specialAttack: 40,
    specialDefense: 40,
    speed: 41,
    generation: 1,
    legendary: false
  },
  {
    id: 30,
    name: "Nidorina",
    firstType: "Poison",
    secondType: "",
    total: 365,
    hp: 70,
    attack: 62,
    defense: 67,
    specialAttack: 55,
    specialDefense: 55,
    speed: 56,
    generation: 1,
    legendary: false
  },
  {
    id: 31,
    name: "Nidoqueen",
    firstType: "Poison",
    secondType: "Ground",
    total: 505,
    hp: 90,
    attack: 92,
    defense: 87,
    specialAttack: 75,
    specialDefense: 85,
    speed: 76,
    generation: 1,
    legendary: false
  },
  {
    id: 32,
    name: "Nidoran♂",
    firstType: "Poison",
    secondType: "",
    total: 273,
    hp: 46,
    attack: 57,
    defense: 40,
    specialAttack: 40,
    specialDefense: 40,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 33,
    name: "Nidorino",
    firstType: "Poison",
    secondType: "",
    total: 365,
    hp: 61,
    attack: 72,
    defense: 57,
    specialAttack: 55,
    specialDefense: 55,
    speed: 65,
    generation: 1,
    legendary: false
  },
  {
    id: 34,
    name: "Nidoking",
    firstType: "Poison",
    secondType: "Ground",
    total: 505,
    hp: 81,
    attack: 102,
    defense: 77,
    specialAttack: 85,
    specialDefense: 75,
    speed: 85,
    generation: 1,
    legendary: false
  },
  {
    id: 35,
    name: "Clefairy",
    firstType: "Fairy",
    secondType: "",
    total: 323,
    hp: 70,
    attack: 45,
    defense: 48,
    specialAttack: 60,
    specialDefense: 65,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 36,
    name: "Clefable",
    firstType: "Fairy",
    secondType: "",
    total: 483,
    hp: 95,
    attack: 70,
    defense: 73,
    specialAttack: 95,
    specialDefense: 90,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 37,
    name: "Vulpix",
    firstType: "Fire",
    secondType: "",
    total: 299,
    hp: 38,
    attack: 41,
    defense: 40,
    specialAttack: 50,
    specialDefense: 65,
    speed: 65,
    generation: 1,
    legendary: false
  },
  {
    id: 38,
    name: "Ninetales",
    firstType: "Fire",
    secondType: "",
    total: 505,
    hp: 73,
    attack: 76,
    defense: 75,
    specialAttack: 81,
    specialDefense: 100,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 39,
    name: "Jigglypuff",
    firstType: "Normal",
    secondType: "Fairy",
    total: 270,
    hp: 115,
    attack: 45,
    defense: 20,
    specialAttack: 45,
    specialDefense: 25,
    speed: 20,
    generation: 1,
    legendary: false
  },
  {
    id: 40,
    name: "Wigglytuff",
    firstType: "Normal",
    secondType: "Fairy",
    total: 435,
    hp: 140,
    attack: 70,
    defense: 45,
    specialAttack: 85,
    specialDefense: 50,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 41,
    name: "Zubat",
    firstType: "Poison",
    secondType: "Flying",
    total: 245,
    hp: 40,
    attack: 45,
    defense: 35,
    specialAttack: 30,
    specialDefense: 40,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 42,
    name: "Golbat",
    firstType: "Poison",
    secondType: "Flying",
    total: 455,
    hp: 75,
    attack: 80,
    defense: 70,
    specialAttack: 65,
    specialDefense: 75,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 43,
    name: "Oddish",
    firstType: "Grass",
    secondType: "Poison",
    total: 320,
    hp: 45,
    attack: 50,
    defense: 55,
    specialAttack: 75,
    specialDefense: 65,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 44,
    name: "Gloom",
    firstType: "Grass",
    secondType: "Poison",
    total: 395,
    hp: 60,
    attack: 65,
    defense: 70,
    specialAttack: 85,
    specialDefense: 75,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 45,
    name: "Vileplume",
    firstType: "Grass",
    secondType: "Poison",
    total: 490,
    hp: 75,
    attack: 80,
    defense: 85,
    specialAttack: 110,
    specialDefense: 90,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 46,
    name: "Paras",
    firstType: "Bug",
    secondType: "Grass",
    total: 285,
    hp: 35,
    attack: 70,
    defense: 55,
    specialAttack: 45,
    specialDefense: 55,
    speed: 25,
    generation: 1,
    legendary: false
  },
  {
    id: 47,
    name: "Parasect",
    firstType: "Bug",
    secondType: "Grass",
    total: 405,
    hp: 60,
    attack: 95,
    defense: 80,
    specialAttack: 60,
    specialDefense: 80,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 48,
    name: "Venonat",
    firstType: "Bug",
    secondType: "Poison",
    total: 305,
    hp: 60,
    attack: 55,
    defense: 50,
    specialAttack: 40,
    specialDefense: 55,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 49,
    name: "Venomoth",
    firstType: "Bug",
    secondType: "Poison",
    total: 450,
    hp: 70,
    attack: 65,
    defense: 60,
    specialAttack: 90,
    specialDefense: 75,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 50,
    name: "Diglett",
    firstType: "Ground",
    secondType: "",
    total: 265,
    hp: 10,
    attack: 55,
    defense: 25,
    specialAttack: 35,
    specialDefense: 45,
    speed: 95,
    generation: 1,
    legendary: false
  },
  {
    id: 51,
    name: "Dugtrio",
    firstType: "Ground",
    secondType: "",
    total: 405,
    hp: 35,
    attack: 80,
    defense: 50,
    specialAttack: 50,
    specialDefense: 70,
    speed: 120,
    generation: 1,
    legendary: false
  },
  {
    id: 52,
    name: "Meowth",
    firstType: "Normal",
    secondType: "",
    total: 290,
    hp: 40,
    attack: 45,
    defense: 35,
    specialAttack: 40,
    specialDefense: 40,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 53,
    name: "Persian",
    firstType: "Normal",
    secondType: "",
    total: 440,
    hp: 65,
    attack: 70,
    defense: 60,
    specialAttack: 65,
    specialDefense: 65,
    speed: 115,
    generation: 1,
    legendary: false
  },
  {
    id: 54,
    name: "Psyduck",
    firstType: "Water",
    secondType: "",
    total: 320,
    hp: 50,
    attack: 52,
    defense: 48,
    specialAttack: 65,
    specialDefense: 50,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 55,
    name: "Golduck",
    firstType: "Water",
    secondType: "",
    total: 500,
    hp: 80,
    attack: 82,
    defense: 78,
    specialAttack: 95,
    specialDefense: 80,
    speed: 85,
    generation: 1,
    legendary: false
  },
  {
    id: 56,
    name: "Mankey",
    firstType: "Fighting",
    secondType: "",
    total: 305,
    hp: 40,
    attack: 80,
    defense: 35,
    specialAttack: 35,
    specialDefense: 45,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 57,
    name: "Primeape",
    firstType: "Fighting",
    secondType: "",
    total: 455,
    hp: 65,
    attack: 105,
    defense: 60,
    specialAttack: 60,
    specialDefense: 70,
    speed: 95,
    generation: 1,
    legendary: false
  },
  {
    id: 58,
    name: "Growlithe",
    firstType: "Fire",
    secondType: "",
    total: 350,
    hp: 55,
    attack: 70,
    defense: 45,
    specialAttack: 70,
    specialDefense: 50,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 59,
    name: "Arcanine",
    firstType: "Fire",
    secondType: "",
    total: 555,
    hp: 90,
    attack: 110,
    defense: 80,
    specialAttack: 100,
    specialDefense: 80,
    speed: 95,
    generation: 1,
    legendary: false
  },
  {
    id: 60,
    name: "Poliwag",
    firstType: "Water",
    secondType: "",
    total: 300,
    hp: 40,
    attack: 50,
    defense: 40,
    specialAttack: 40,
    specialDefense: 40,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 61,
    name: "Poliwhirl",
    firstType: "Water",
    secondType: "",
    total: 385,
    hp: 65,
    attack: 65,
    defense: 65,
    specialAttack: 50,
    specialDefense: 50,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 62,
    name: "Poliwrath",
    firstType: "Water",
    secondType: "Fighting",
    total: 510,
    hp: 90,
    attack: 95,
    defense: 95,
    specialAttack: 70,
    specialDefense: 90,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 63,
    name: "Abra",
    firstType: "Psychic",
    secondType: "",
    total: 310,
    hp: 25,
    attack: 20,
    defense: 15,
    specialAttack: 105,
    specialDefense: 55,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 64,
    name: "Kadabra",
    firstType: "Psychic",
    secondType: "",
    total: 400,
    hp: 40,
    attack: 35,
    defense: 30,
    specialAttack: 120,
    specialDefense: 70,
    speed: 105,
    generation: 1,
    legendary: false
  },
  {
    id: 65,
    name: "Alakazam",
    firstType: "Psychic",
    secondType: "",
    total: 500,
    hp: 55,
    attack: 50,
    defense: 45,
    specialAttack: 135,
    specialDefense: 95,
    speed: 120,
    generation: 1,
    legendary: false
  },
  {
    id: 65,
    name: "AlakazamMega Alakazam",
    firstType: "Psychic",
    secondType: "",
    total: 590,
    hp: 55,
    attack: 50,
    defense: 65,
    specialAttack: 175,
    specialDefense: 95,
    speed: 150,
    generation: 1,
    legendary: false
  },
  {
    id: 66,
    name: "Machop",
    firstType: "Fighting",
    secondType: "",
    total: 305,
    hp: 70,
    attack: 80,
    defense: 50,
    specialAttack: 35,
    specialDefense: 35,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 67,
    name: "Machoke",
    firstType: "Fighting",
    secondType: "",
    total: 405,
    hp: 80,
    attack: 100,
    defense: 70,
    specialAttack: 50,
    specialDefense: 60,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 68,
    name: "Machamp",
    firstType: "Fighting",
    secondType: "",
    total: 505,
    hp: 90,
    attack: 130,
    defense: 80,
    specialAttack: 65,
    specialDefense: 85,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 69,
    name: "Bellsprout",
    firstType: "Grass",
    secondType: "Poison",
    total: 300,
    hp: 50,
    attack: 75,
    defense: 35,
    specialAttack: 70,
    specialDefense: 30,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 70,
    name: "Weepinbell",
    firstType: "Grass",
    secondType: "Poison",
    total: 390,
    hp: 65,
    attack: 90,
    defense: 50,
    specialAttack: 85,
    specialDefense: 45,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 71,
    name: "Victreebel",
    firstType: "Grass",
    secondType: "Poison",
    total: 490,
    hp: 80,
    attack: 105,
    defense: 65,
    specialAttack: 100,
    specialDefense: 70,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 72,
    name: "Tentacool",
    firstType: "Water",
    secondType: "Poison",
    total: 335,
    hp: 40,
    attack: 40,
    defense: 35,
    specialAttack: 50,
    specialDefense: 100,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 73,
    name: "Tentacruel",
    firstType: "Water",
    secondType: "Poison",
    total: 515,
    hp: 80,
    attack: 70,
    defense: 65,
    specialAttack: 80,
    specialDefense: 120,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 74,
    name: "Geodude",
    firstType: "Rock",
    secondType: "Ground",
    total: 300,
    hp: 40,
    attack: 80,
    defense: 100,
    specialAttack: 30,
    specialDefense: 30,
    speed: 20,
    generation: 1,
    legendary: false
  },
  {
    id: 75,
    name: "Graveler",
    firstType: "Rock",
    secondType: "Ground",
    total: 390,
    hp: 55,
    attack: 95,
    defense: 115,
    specialAttack: 45,
    specialDefense: 45,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 76,
    name: "Golem",
    firstType: "Rock",
    secondType: "Ground",
    total: 495,
    hp: 80,
    attack: 120,
    defense: 130,
    specialAttack: 55,
    specialDefense: 65,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 77,
    name: "Ponyta",
    firstType: "Fire",
    secondType: "",
    total: 410,
    hp: 50,
    attack: 85,
    defense: 55,
    specialAttack: 65,
    specialDefense: 65,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 78,
    name: "Rapidash",
    firstType: "Fire",
    secondType: "",
    total: 500,
    hp: 65,
    attack: 100,
    defense: 70,
    specialAttack: 80,
    specialDefense: 80,
    speed: 105,
    generation: 1,
    legendary: false
  },
  {
    id: 79,
    name: "Slowpoke",
    firstType: "Water",
    secondType: "Psychic",
    total: 315,
    hp: 90,
    attack: 65,
    defense: 65,
    specialAttack: 40,
    specialDefense: 40,
    speed: 15,
    generation: 1,
    legendary: false
  },
  {
    id: 80,
    name: "Slowbro",
    firstType: "Water",
    secondType: "Psychic",
    total: 490,
    hp: 95,
    attack: 75,
    defense: 110,
    specialAttack: 100,
    specialDefense: 80,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 80,
    name: "SlowbroMega Slowbro",
    firstType: "Water",
    secondType: "Psychic",
    total: 590,
    hp: 95,
    attack: 75,
    defense: 180,
    specialAttack: 130,
    specialDefense: 80,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 81,
    name: "Magnemite",
    firstType: "Electric",
    secondType: "Steel",
    total: 325,
    hp: 25,
    attack: 35,
    defense: 70,
    specialAttack: 95,
    specialDefense: 55,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 82,
    name: "Magneton",
    firstType: "Electric",
    secondType: "Steel",
    total: 465,
    hp: 50,
    attack: 60,
    defense: 95,
    specialAttack: 120,
    specialDefense: 70,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 83,
    name: "Farfetch'd",
    firstType: "Normal",
    secondType: "Flying",
    total: 352,
    hp: 52,
    attack: 65,
    defense: 55,
    specialAttack: 58,
    specialDefense: 62,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 84,
    name: "Doduo",
    firstType: "Normal",
    secondType: "Flying",
    total: 310,
    hp: 35,
    attack: 85,
    defense: 45,
    specialAttack: 35,
    specialDefense: 35,
    speed: 75,
    generation: 1,
    legendary: false
  },
  {
    id: 85,
    name: "Dodrio",
    firstType: "Normal",
    secondType: "Flying",
    total: 460,
    hp: 60,
    attack: 110,
    defense: 70,
    specialAttack: 60,
    specialDefense: 60,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 86,
    name: "Seel",
    firstType: "Water",
    secondType: "",
    total: 325,
    hp: 65,
    attack: 45,
    defense: 55,
    specialAttack: 45,
    specialDefense: 70,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 87,
    name: "Dewgong",
    firstType: "Water",
    secondType: "Ice",
    total: 475,
    hp: 90,
    attack: 70,
    defense: 80,
    specialAttack: 70,
    specialDefense: 95,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 88,
    name: "Grimer",
    firstType: "Poison",
    secondType: "",
    total: 325,
    hp: 80,
    attack: 80,
    defense: 50,
    specialAttack: 40,
    specialDefense: 50,
    speed: 25,
    generation: 1,
    legendary: false
  },
  {
    id: 89,
    name: "Muk",
    firstType: "Poison",
    secondType: "",
    total: 500,
    hp: 105,
    attack: 105,
    defense: 75,
    specialAttack: 65,
    specialDefense: 100,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 90,
    name: "Shellder",
    firstType: "Water",
    secondType: "",
    total: 305,
    hp: 30,
    attack: 65,
    defense: 100,
    specialAttack: 45,
    specialDefense: 25,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 91,
    name: "Cloyster",
    firstType: "Water",
    secondType: "Ice",
    total: 525,
    hp: 50,
    attack: 95,
    defense: 180,
    specialAttack: 85,
    specialDefense: 45,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 92,
    name: "Gastly",
    firstType: "Ghost",
    secondType: "Poison",
    total: 310,
    hp: 30,
    attack: 35,
    defense: 30,
    specialAttack: 100,
    specialDefense: 35,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 93,
    name: "Haunter",
    firstType: "Ghost",
    secondType: "Poison",
    total: 405,
    hp: 45,
    attack: 50,
    defense: 45,
    specialAttack: 115,
    specialDefense: 55,
    speed: 95,
    generation: 1,
    legendary: false
  },
  {
    id: 94,
    name: "Gengar",
    firstType: "Ghost",
    secondType: "Poison",
    total: 500,
    hp: 60,
    attack: 65,
    defense: 60,
    specialAttack: 130,
    specialDefense: 75,
    speed: 110,
    generation: 1,
    legendary: false
  },
  {
    id: 94,
    name: "GengarMega Gengar",
    firstType: "Ghost",
    secondType: "Poison",
    total: 600,
    hp: 60,
    attack: 65,
    defense: 80,
    specialAttack: 170,
    specialDefense: 95,
    speed: 130,
    generation: 1,
    legendary: false
  },
  {
    id: 95,
    name: "Onix",
    firstType: "Rock",
    secondType: "Ground",
    total: 385,
    hp: 35,
    attack: 45,
    defense: 160,
    specialAttack: 30,
    specialDefense: 45,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 96,
    name: "Drowzee",
    firstType: "Psychic",
    secondType: "",
    total: 328,
    hp: 60,
    attack: 48,
    defense: 45,
    specialAttack: 43,
    specialDefense: 90,
    speed: 42,
    generation: 1,
    legendary: false
  },
  {
    id: 97,
    name: "Hypno",
    firstType: "Psychic",
    secondType: "",
    total: 483,
    hp: 85,
    attack: 73,
    defense: 70,
    specialAttack: 73,
    specialDefense: 115,
    speed: 67,
    generation: 1,
    legendary: false
  },
  {
    id: 98,
    name: "Krabby",
    firstType: "Water",
    secondType: "",
    total: 325,
    hp: 30,
    attack: 105,
    defense: 90,
    specialAttack: 25,
    specialDefense: 25,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 99,
    name: "Kingler",
    firstType: "Water",
    secondType: "",
    total: 475,
    hp: 55,
    attack: 130,
    defense: 115,
    specialAttack: 50,
    specialDefense: 50,
    speed: 75,
    generation: 1,
    legendary: false
  },
  {
    id: 100,
    name: "Voltorb",
    firstType: "Electric",
    secondType: "",
    total: 330,
    hp: 40,
    attack: 30,
    defense: 50,
    specialAttack: 55,
    specialDefense: 55,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 101,
    name: "Electrode",
    firstType: "Electric",
    secondType: "",
    total: 480,
    hp: 60,
    attack: 50,
    defense: 70,
    specialAttack: 80,
    specialDefense: 80,
    speed: 140,
    generation: 1,
    legendary: false
  },
  {
    id: 102,
    name: "Exeggcute",
    firstType: "Grass",
    secondType: "Psychic",
    total: 325,
    hp: 60,
    attack: 40,
    defense: 80,
    specialAttack: 60,
    specialDefense: 45,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 103,
    name: "Exeggutor",
    firstType: "Grass",
    secondType: "Psychic",
    total: 520,
    hp: 95,
    attack: 95,
    defense: 85,
    specialAttack: 125,
    specialDefense: 65,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 104,
    name: "Cubone",
    firstType: "Ground",
    secondType: "",
    total: 320,
    hp: 50,
    attack: 50,
    defense: 95,
    specialAttack: 40,
    specialDefense: 50,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 105,
    name: "Marowak",
    firstType: "Ground",
    secondType: "",
    total: 425,
    hp: 60,
    attack: 80,
    defense: 110,
    specialAttack: 50,
    specialDefense: 80,
    speed: 45,
    generation: 1,
    legendary: false
  },
  {
    id: 106,
    name: "Hitmonlee",
    firstType: "Fighting",
    secondType: "",
    total: 455,
    hp: 50,
    attack: 120,
    defense: 53,
    specialAttack: 35,
    specialDefense: 110,
    speed: 87,
    generation: 1,
    legendary: false
  },
  {
    id: 107,
    name: "Hitmonchan",
    firstType: "Fighting",
    secondType: "",
    total: 455,
    hp: 50,
    attack: 105,
    defense: 79,
    specialAttack: 35,
    specialDefense: 110,
    speed: 76,
    generation: 1,
    legendary: false
  },
  {
    id: 108,
    name: "Lickitung",
    firstType: "Normal",
    secondType: "",
    total: 385,
    hp: 90,
    attack: 55,
    defense: 75,
    specialAttack: 60,
    specialDefense: 75,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 109,
    name: "Koffing",
    firstType: "Poison",
    secondType: "",
    total: 340,
    hp: 40,
    attack: 65,
    defense: 95,
    specialAttack: 60,
    specialDefense: 45,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 110,
    name: "Weezing",
    firstType: "Poison",
    secondType: "",
    total: 490,
    hp: 65,
    attack: 90,
    defense: 120,
    specialAttack: 85,
    specialDefense: 70,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 111,
    name: "Rhyhorn",
    firstType: "Ground",
    secondType: "Rock",
    total: 345,
    hp: 80,
    attack: 85,
    defense: 95,
    specialAttack: 30,
    specialDefense: 30,
    speed: 25,
    generation: 1,
    legendary: false
  },
  {
    id: 112,
    name: "Rhydon",
    firstType: "Ground",
    secondType: "Rock",
    total: 485,
    hp: 105,
    attack: 130,
    defense: 120,
    specialAttack: 45,
    specialDefense: 45,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 113,
    name: "Chansey",
    firstType: "Normal",
    secondType: "",
    total: 450,
    hp: 250,
    attack: 5,
    defense: 5,
    specialAttack: 35,
    specialDefense: 105,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 114,
    name: "Tangela",
    firstType: "Grass",
    secondType: "",
    total: 435,
    hp: 65,
    attack: 55,
    defense: 115,
    specialAttack: 100,
    specialDefense: 40,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 115,
    name: "Kangaskhan",
    firstType: "Normal",
    secondType: "",
    total: 490,
    hp: 105,
    attack: 95,
    defense: 80,
    specialAttack: 40,
    specialDefense: 80,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 115,
    name: "KangaskhanMega Kangaskhan",
    firstType: "Normal",
    secondType: "",
    total: 590,
    hp: 105,
    attack: 125,
    defense: 100,
    specialAttack: 60,
    specialDefense: 100,
    speed: 100,
    generation: 1,
    legendary: false
  },
  {
    id: 116,
    name: "Horsea",
    firstType: "Water",
    secondType: "",
    total: 295,
    hp: 30,
    attack: 40,
    defense: 70,
    specialAttack: 70,
    specialDefense: 25,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 117,
    name: "Seadra",
    firstType: "Water",
    secondType: "",
    total: 440,
    hp: 55,
    attack: 65,
    defense: 95,
    specialAttack: 95,
    specialDefense: 45,
    speed: 85,
    generation: 1,
    legendary: false
  },
  {
    id: 118,
    name: "Goldeen",
    firstType: "Water",
    secondType: "",
    total: 320,
    hp: 45,
    attack: 67,
    defense: 60,
    specialAttack: 35,
    specialDefense: 50,
    speed: 63,
    generation: 1,
    legendary: false
  },
  {
    id: 119,
    name: "Seaking",
    firstType: "Water",
    secondType: "",
    total: 450,
    hp: 80,
    attack: 92,
    defense: 65,
    specialAttack: 65,
    specialDefense: 80,
    speed: 68,
    generation: 1,
    legendary: false
  },
  {
    id: 120,
    name: "Staryu",
    firstType: "Water",
    secondType: "",
    total: 340,
    hp: 30,
    attack: 45,
    defense: 55,
    specialAttack: 70,
    specialDefense: 55,
    speed: 85,
    generation: 1,
    legendary: false
  },
  {
    id: 121,
    name: "Starmie",
    firstType: "Water",
    secondType: "Psychic",
    total: 520,
    hp: 60,
    attack: 75,
    defense: 85,
    specialAttack: 100,
    specialDefense: 85,
    speed: 115,
    generation: 1,
    legendary: false
  },
  {
    id: 122,
    name: "Mr. Mime",
    firstType: "Psychic",
    secondType: "Fairy",
    total: 460,
    hp: 40,
    attack: 45,
    defense: 65,
    specialAttack: 100,
    specialDefense: 120,
    speed: 90,
    generation: 1,
    legendary: false
  },
  {
    id: 123,
    name: "Scyther",
    firstType: "Bug",
    secondType: "Flying",
    total: 500,
    hp: 70,
    attack: 110,
    defense: 80,
    specialAttack: 55,
    specialDefense: 80,
    speed: 105,
    generation: 1,
    legendary: false
  },
  {
    id: 124,
    name: "Jynx",
    firstType: "Ice",
    secondType: "Psychic",
    total: 455,
    hp: 65,
    attack: 50,
    defense: 35,
    specialAttack: 115,
    specialDefense: 95,
    speed: 95,
    generation: 1,
    legendary: false
  },
  {
    id: 125,
    name: "Electabuzz",
    firstType: "Electric",
    secondType: "",
    total: 490,
    hp: 65,
    attack: 83,
    defense: 57,
    specialAttack: 95,
    specialDefense: 85,
    speed: 105,
    generation: 1,
    legendary: false
  },
  {
    id: 126,
    name: "Magmar",
    firstType: "Fire",
    secondType: "",
    total: 495,
    hp: 65,
    attack: 95,
    defense: 57,
    specialAttack: 100,
    specialDefense: 85,
    speed: 93,
    generation: 1,
    legendary: false
  },
  {
    id: 127,
    name: "Pinsir",
    firstType: "Bug",
    secondType: "",
    total: 500,
    hp: 65,
    attack: 125,
    defense: 100,
    specialAttack: 55,
    specialDefense: 70,
    speed: 85,
    generation: 1,
    legendary: false
  },
  {
    id: 127,
    name: "PinsirMega Pinsir",
    firstType: "Bug",
    secondType: "Flying",
    total: 600,
    hp: 65,
    attack: 155,
    defense: 120,
    specialAttack: 65,
    specialDefense: 90,
    speed: 105,
    generation: 1,
    legendary: false
  },
  {
    id: 128,
    name: "Tauros",
    firstType: "Normal",
    secondType: "",
    total: 490,
    hp: 75,
    attack: 100,
    defense: 95,
    specialAttack: 40,
    specialDefense: 70,
    speed: 110,
    generation: 1,
    legendary: false
  },
  {
    id: 129,
    name: "Magikarp",
    firstType: "Water",
    secondType: "",
    total: 200,
    hp: 20,
    attack: 10,
    defense: 55,
    specialAttack: 15,
    specialDefense: 20,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 130,
    name: "Gyarados",
    firstType: "Water",
    secondType: "Flying",
    total: 540,
    hp: 95,
    attack: 125,
    defense: 79,
    specialAttack: 60,
    specialDefense: 100,
    speed: 81,
    generation: 1,
    legendary: false
  },
  {
    id: 130,
    name: "GyaradosMega Gyarados",
    firstType: "Water",
    secondType: "Dark",
    total: 640,
    hp: 95,
    attack: 155,
    defense: 109,
    specialAttack: 70,
    specialDefense: 130,
    speed: 81,
    generation: 1,
    legendary: false
  },
  {
    id: 131,
    name: "Lapras",
    firstType: "Water",
    secondType: "Ice",
    total: 535,
    hp: 130,
    attack: 85,
    defense: 80,
    specialAttack: 85,
    specialDefense: 95,
    speed: 60,
    generation: 1,
    legendary: false
  },
  {
    id: 132,
    name: "Ditto",
    firstType: "Normal",
    secondType: "",
    total: 288,
    hp: 48,
    attack: 48,
    defense: 48,
    specialAttack: 48,
    specialDefense: 48,
    speed: 48,
    generation: 1,
    legendary: false
  },
  {
    id: 133,
    name: "Eevee",
    firstType: "Normal",
    secondType: "",
    total: 325,
    hp: 55,
    attack: 55,
    defense: 50,
    specialAttack: 45,
    specialDefense: 65,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 134,
    name: "Vaporeon",
    firstType: "Water",
    secondType: "",
    total: 525,
    hp: 130,
    attack: 65,
    defense: 60,
    specialAttack: 110,
    specialDefense: 95,
    speed: 65,
    generation: 1,
    legendary: false
  },
  {
    id: 135,
    name: "Jolteon",
    firstType: "Electric",
    secondType: "",
    total: 525,
    hp: 65,
    attack: 65,
    defense: 60,
    specialAttack: 110,
    specialDefense: 95,
    speed: 130,
    generation: 1,
    legendary: false
  },
  {
    id: 136,
    name: "Flareon",
    firstType: "Fire",
    secondType: "",
    total: 525,
    hp: 65,
    attack: 130,
    defense: 60,
    specialAttack: 95,
    specialDefense: 110,
    speed: 65,
    generation: 1,
    legendary: false
  },
  {
    id: 137,
    name: "Porygon",
    firstType: "Normal",
    secondType: "",
    total: 395,
    hp: 65,
    attack: 60,
    defense: 70,
    specialAttack: 85,
    specialDefense: 75,
    speed: 40,
    generation: 1,
    legendary: false
  },
  {
    id: 138,
    name: "Omanyte",
    firstType: "Rock",
    secondType: "Water",
    total: 355,
    hp: 35,
    attack: 40,
    defense: 100,
    specialAttack: 90,
    specialDefense: 55,
    speed: 35,
    generation: 1,
    legendary: false
  },
  {
    id: 139,
    name: "Omastar",
    firstType: "Rock",
    secondType: "Water",
    total: 495,
    hp: 70,
    attack: 60,
    defense: 125,
    specialAttack: 115,
    specialDefense: 70,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 140,
    name: "Kabuto",
    firstType: "Rock",
    secondType: "Water",
    total: 355,
    hp: 30,
    attack: 80,
    defense: 90,
    specialAttack: 55,
    specialDefense: 45,
    speed: 55,
    generation: 1,
    legendary: false
  },
  {
    id: 141,
    name: "Kabutops",
    firstType: "Rock",
    secondType: "Water",
    total: 495,
    hp: 60,
    attack: 115,
    defense: 105,
    specialAttack: 65,
    specialDefense: 70,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 142,
    name: "Aerodactyl",
    firstType: "Rock",
    secondType: "Flying",
    total: 515,
    hp: 80,
    attack: 105,
    defense: 65,
    specialAttack: 60,
    specialDefense: 75,
    speed: 130,
    generation: 1,
    legendary: false
  },
  {
    id: 142,
    name: "AerodactylMega Aerodactyl",
    firstType: "Rock",
    secondType: "Flying",
    total: 615,
    hp: 80,
    attack: 135,
    defense: 85,
    specialAttack: 70,
    specialDefense: 95,
    speed: 150,
    generation: 1,
    legendary: false
  },
  {
    id: 143,
    name: "Snorlax",
    firstType: "Normal",
    secondType: "",
    total: 540,
    hp: 160,
    attack: 110,
    defense: 65,
    specialAttack: 65,
    specialDefense: 110,
    speed: 30,
    generation: 1,
    legendary: false
  },
  {
    id: 144,
    name: "Articuno",
    firstType: "Ice",
    secondType: "Flying",
    total: 580,
    hp: 90,
    attack: 85,
    defense: 100,
    specialAttack: 95,
    specialDefense: 125,
    speed: 85,
    generation: 1,
    legendary: true
  },
  {
    id: 145,
    name: "Zapdos",
    firstType: "Electric",
    secondType: "Flying",
    total: 580,
    hp: 90,
    attack: 90,
    defense: 85,
    specialAttack: 125,
    specialDefense: 90,
    speed: 100,
    generation: 1,
    legendary: true
  },
  {
    id: 146,
    name: "Moltres",
    firstType: "Fire",
    secondType: "Flying",
    total: 580,
    hp: 90,
    attack: 100,
    defense: 90,
    specialAttack: 125,
    specialDefense: 85,
    speed: 90,
    generation: 1,
    legendary: true
  },
  {
    id: 147,
    name: "Dratini",
    firstType: "Dragon",
    secondType: "",
    total: 300,
    hp: 41,
    attack: 64,
    defense: 45,
    specialAttack: 50,
    specialDefense: 50,
    speed: 50,
    generation: 1,
    legendary: false
  },
  {
    id: 148,
    name: "Dragonair",
    firstType: "Dragon",
    secondType: "",
    total: 420,
    hp: 61,
    attack: 84,
    defense: 65,
    specialAttack: 70,
    specialDefense: 70,
    speed: 70,
    generation: 1,
    legendary: false
  },
  {
    id: 149,
    name: "Dragonite",
    firstType: "Dragon",
    secondType: "Flying",
    total: 600,
    hp: 91,
    attack: 134,
    defense: 95,
    specialAttack: 100,
    specialDefense: 100,
    speed: 80,
    generation: 1,
    legendary: false
  },
  {
    id: 150,
    name: "Mewtwo",
    firstType: "Psychic",
    secondType: "",
    total: 680,
    hp: 106,
    attack: 110,
    defense: 90,
    specialAttack: 154,
    specialDefense: 90,
    speed: 130,
    generation: 1,
    legendary: true
  },
  {
    id: 150,
    name: "MewtwoMega Mewtwo X",
    firstType: "Psychic",
    secondType: "Fighting",
    total: 780,
    hp: 106,
    attack: 190,
    defense: 100,
    specialAttack: 154,
    specialDefense: 100,
    speed: 130,
    generation: 1,
    legendary: true
  },
  {
    id: 150,
    name: "MewtwoMega Mewtwo Y",
    firstType: "Psychic",
    secondType: "",
    total: 780,
    hp: 106,
    attack: 150,
    defense: 70,
    specialAttack: 194,
    specialDefense: 120,
    speed: 140,
    generation: 1,
    legendary: true
  },
  {
    id: 151,
    name: "Mew",
    firstType: "Psychic",
    secondType: "",
    total: 600,
    hp: 100,
    attack: 100,
    defense: 100,
    specialAttack: 100,
    specialDefense: 100,
    speed: 100,
    generation: 1,
    legendary: false
  }
];
